### PR TITLE
Add Vicon support

### LINKED ISSUE #27: Vicon Integration
Add support for Vicon position input

### PR DESCRIPTION
**Pull request by rob-clarke**
Adds a Vicon image build `starling-vicon`

TODO:
- [x] Documentation
- [x] Submodule path
- [x] Submodule code quality
- [x] Decide on deployment strategy

Closes #27

### CODE REVIEW

**Comment by rob-clarke** [comment]
@mhl787156 wrt deployment strategy, what are your thoughts?

I see a few options:
- Deploy separate nodes as their own DaemonSet
- Deploy separate nodes as part of the MAVROS DaemonSet
- Deploy a single translator node that handles all Vicon objects

**Comment by mhl787156** [comment]
I think we should Deploy separate nodes as their own DaemonSet. 
This enforces 'realistic architectures' as it mirrors GPS, it also means we get separation of concerns. 
They shouldn't be included in MAVROS as that would bloat requirements of simulated drones.

**Comment by rob-clarke** [comment]
The main risk as I see it is that it adds to the number of containers that need to be run on the Pi which you said started to struggle after a couple.

**Comment by mhl787156** [comment]
Hmmm I think the only way to know is by testing it - when it was running the MAVROS, clover lights and vicon the other day, it was at 50% cpu and 1Gb Ram so its still okay for now.

**Comment by rob-clarke** [comment]
Submodule quality somewhat improved. Needs testing...

**Comment by mhl787156** [comment]
It all looks good, happy to merge

**Pull request merged**
